### ISSUE TITLE
IMPROVE THIS DOC gives 404

### ISSUE THREAD

**Issue by cron410** [resin-io/docs#594] opened 2017-09-26 17:47 UTC
https://docs.resin.io/nuc/nodejs/getting-started/

![image](https://user-images.githubusercontent.com/3082899/30875313-202f6544-a2c1-11e7-9ba8-d687cde109d6.png)

https://github.com/resin-io/docs/edit/master/pages/nuc/nodejs/getting-started.md

**Comment by zwalchuk** [comment] 2017-12-05 16:02
Duplicate of #563

**Closed by zwalchuk** 2017-12-05 16:02 UTC
Labels: duplicate
