### ISSUE TITLE
Dockerfile deployment guide should mention `.templates`

### ISSUE THREAD

**Issue by shaunmulligan** [resin-io/docs#284] opened 2016-08-08 21:06 UTC
We should mention `Dockerfile.template` in the deployment guide and speak specifically about the order of preference in the builder, namely:
`Dockerfile.template` -> `Dockerfile` -> `package.json`

**Comment by zwalchuk** [comment] 2017-12-05 16:38
We have a [Dockerfile template page](https://docs.resin.io/deployment/docker-templates/), but it is not linked to in the Dockerfile guide. Should probably just be incorporated into that page

**Comment by zwalchuk** [comment] 2018-02-09 18:21
duplicate of #290

**Closed by zwalchuk** 2018-02-09 18:21 UTC
Labels: status/duplicate
