### ISSUE TITLE
Improve the Edit this doc button

### ISSUE THREAD

**Issue by emirotin** [resin-io/docs#300] opened 2016-08-18 08:59 UTC
The button currently opens the file on github corresponding to the current page.

It fails for some cases, namely:
- dynamic pages (the button goes to the current page URL which does not correspond to the actual file location)
- partials (the button knows nothing about them)
- external docs (they can be edited, but that change will be neglected on the consequent deploy)

The proper fixes are quite sophisticated (especially for partials), so I leave it as a reminder that we should deal with it).

**Comment by zwalchuk** [comment] 2017-12-05 16:49
Duplicate of #563

**Closed by zwalchuk** 2017-12-05 16:49 UTC
Labels: duplicate
