### ISSUE TITLE
Importance of sync after writing stuff to /data

### ISSUE THREAD

**Issue by shaunmulligan** [resin-io/docs#311] opened 2016-08-30 10:02 UTC
sometimes user restart or reboot and notice that their data is not actually persisted in /data. usually they have not run `sync` beforehand.

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_lei)

**Comment by zwalchuk** [comment] 2017-12-05 16:51
duplicate of #197

**Closed by zwalchuk** 2017-12-05 16:51 UTC
Labels: easy, enhancement, runtime-docs
